//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.pro.adapter;

import android.content.Context;

public final class CategoryBigAdapter_
    extends CategoryBigAdapter
{

    private Context context_;

    private CategoryBigAdapter_(Context context) {
        context_ = context;
        init_();
    }

    public static CategoryBigAdapter_ getInstance_(Context context) {
        return new CategoryBigAdapter_(context);
    }

    private void init_() {
        context = context_;
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
