//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.pro.adapter;

import android.content.Context;

public final class CategoryAdapter_
    extends CategoryAdapter
{

    private Context context_;

    private CategoryAdapter_(Context context) {
        context_ = context;
        init_();
    }

    public static CategoryAdapter_ getInstance_(Context context) {
        return new CategoryAdapter_(context);
    }

    private void init_() {
        context = context_;
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
