//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.pro.adapter;

import android.content.Context;

public final class CategoryGridAdapter_
    extends CategoryGridAdapter
{

    private Context context_;

    private CategoryGridAdapter_(Context context) {
        context_ = context;
        init_();
    }

    public static CategoryGridAdapter_ getInstance_(Context context) {
        return new CategoryGridAdapter_(context);
    }

    private void init_() {
        context = context_;
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
