//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.pro.adapter;

import android.content.Context;

public final class CommunityGridAdapter_
    extends CommunityGridAdapter
{

    private Context context_;

    private CommunityGridAdapter_(Context context) {
        context_ = context;
        init_();
    }

    public static CommunityGridAdapter_ getInstance_(Context context) {
        return new CommunityGridAdapter_(context);
    }

    private void init_() {
        context = context_;
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
