//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.pro.adapter;

import android.content.Context;

public final class CommunityAdapter_
    extends CommunityAdapter
{

    private Context context_;

    private CommunityAdapter_(Context context) {
        context_ = context;
        init_();
    }

    public static CommunityAdapter_ getInstance_(Context context) {
        return new CommunityAdapter_(context);
    }

    private void init_() {
        context = context_;
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
